<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMARTINDONASIA_API_SmokeTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>00df13ad-f07e-4f4e-a134-7026ccbb5072</testSuiteGuid>
   <testCaseLink>
      <guid>f595c92f-d2d1-4e79-b1ee-8886b5a17a30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/a.ValidateMobileNumber_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd256bd6-03fa-4497-9b7e-c03c9e413b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/aValidate_OTPTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>91ff843e-b8e2-470a-8a44-6a2b78edb036</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/bInsertUser_CheckInTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b2552d5-2298-4e40-9913-d6df279e1ff4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b22dd69e-92c5-4135-91ae-8a5f345f7d45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/bUpdateUser_CheckInTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38ac2732-38fe-4e87-abda-281257e4a6d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa51c72d-62db-47ea-ac21-5dbfdfba0ec0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fcd9fa53-02e2-444c-a72b-b80a29b521d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cInsertTripDetails_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90be6f61-c29d-4a01-9f27-f293ef22d746</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26f5116a-5936-48f0-9872-7937fa8764b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3018af5-22bd-4ae8-af63-abc4493bf1af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8595f09-e74f-4a62-aa70-bde712fdd875</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cUpdateTripDetails_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3602633d-47d9-470d-b5c5-4e0c3355a239</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/d.VersionMaster_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8157c325-7a01-450a-99ef-706f84849dab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/dLeaveType_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a665b87-4dea-4011-b03d-7d8f6719bab2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96dbec36-4fdc-4302-9625-6679f91143b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/eLeaveApplication_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e697030a-5144-4711-8673-b3024ec86664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ded0104b-4ad8-4134-b20e-07859c19fd7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aee1834-a9c2-47b8-aac4-a17dcd6afd7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fad04ab8-9366-480c-8c89-6de1823d3da3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7474db37-f279-4f1c-b177-31534f9857ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/eLeaveCancelApplicationTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdb12eb7-5c98-4aeb-9207-42904135d804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b50c391-b896-4a45-990b-337d31dee926</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18ed55e1-ff3e-468e-87fa-acdaa7ba33fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/gCropMasterTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78bbacb7-4d67-47f3-9a6c-12825e15ff81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5be8ec28-2cfd-4b0a-9ac2-1ac8f7ec13b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/hProductMaster_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b132b0-80e5-4e73-822d-6aef7405c2e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d43fd5a-7ae6-48bc-a50c-0a742db3a12d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iUserCropProduct_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>782f6264-b26a-4741-bf5c-75e46f868d08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48df10ce-fa87-41ff-86f3-aa80c6284d5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/jUserGeographyDetails_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68232be-7d31-4216-9608-962bb6f33d64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3110f371-e902-4a65-bd09-09d9be32d5c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/kUserTimeline_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b480f63-7031-45b4-b8c7-2b799126e804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17d0bc24-cfc7-4a62-ad64-a5f3cad0a48a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>125f044b-1b4b-42b3-9c7d-62d02d412183</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/lSeverityMaster_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d73d8464-576d-4b9b-828a-43fa7a80a338</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a86767e3-9ced-4e77-9a7c-a7621e431700</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mQuestionAnswerMaster_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c408c48f-4a09-4883-8cbb-59e5629d6eff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85f59ea1-7688-462f-9baf-5c029b6d9447</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/nHolidayMaster_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10cd017f-5ced-4032-8ec2-2df13cee87a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f748111-6fbc-4d1d-b8c7-b08121a778a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/oRefrenceMaster_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5ac53206-8913-4d11-840c-8d6df1f891af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/pLobByUser_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f000be3c-f673-4645-9699-abb8b26d9281</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/qActivityHistory_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a9af9e0e-4ab4-4686-bb28-8ed2eceae72d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RoleAccessUser_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dc7be2fc-36ef-4505-8e65-d0d81d0f1dfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/sIncidentHistory_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4b503e9e-ce0b-4d83-b407-bf2c9b922676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tMergeContactDetail_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad61b527-db8b-4f58-a8f3-0942bb74628c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f340cd5-6a5c-4d01-9dba-5e42dad4553d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/vInsertIncident_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d04999-399f-4135-81b8-e293f699ff38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7d0227b-5b51-4718-892a-2df28ca2a17a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49e323f4-d702-49ab-91c1-9ba7957354aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/xDasboard_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>758f28f3-61fc-4998-82c0-704346e9685a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/wDiseaseMaster_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5406048a-d4f4-46ab-8bbb-ef575a5c9e82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aac8d4b4-3a87-4780-b0e1-1b7e9b0e8e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/zMobileAppVersion_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5099bd5-3108-4a88-8d84-61367d6589d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>753e88cb-e07f-442b-863d-b97edb68fd91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84607651-e79b-44e5-8678-8c739eca2d57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/zActivityCategory_Test</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71bfbc98-af21-4bb7-97d4-30eaf9c2a567</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72026b88-7910-46d9-abd8-df3b3ebb7c5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/z1SupervisiorTeamStatus_Test</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c9524e59-7ace-4a23-b718-8b1918fec5e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/z2Supervisior Users</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>494d551b-2f25-4fff-b192-fc4499b04709</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/z6MobileTracking_Test--ND</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5993773-eded-48a8-8717-283e8511def7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60928ac3-4f69-44c5-8d85-842e6d1e9973</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3c78ab5-5e40-4b47-8d78-cf207a98c1f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78fcddb3-9496-4dc5-82f1-52c670b2e0c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/x1TargetBreakDown_Test</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
